### ISSUE TITLE
round robin tournament TC 40/2 with 150 games 

### ISSUE THREAD

**Issue by ChessGUI** [lukasmonk/irina#1]
=================================================================================================== 
  Nr Engine                               Pts      SB    pi ti to Ne Vi ir
   1 pierre17                             5.0      7.00  -- 10 -- -- 11 11
   2 tikov                                3.0     10.00  01 -- 01 1 -- --
   3 toledo_nanochess_wb                  3.0      7.00  -- 10 -- 11 -- --
   4 Neurone_XXVI                         2.0      2.00  -- 0 00 -- 11 --
   5 VirutorChessUci_1.1.2                1.0      1.00  00 -- -- 00 -- 01
   6 irina                                1.0      1.00  00 -- -- -- 10 --

 =================================================================================================== 
  Nr Engine                               Pts      SB    to pi ir Ne ti Vi
   1 toledo_nanochess_wb                  7.0     31.25  -- 10 1= 11 10 1=
   2 pierre17                             7.0     30.50  01 -- 11 01 10 11
   3 irina                                5.0     20.75  0= 00 -- =1 11 10
   4 Neurone_XXVI                         4.5     18.50  00 10 =0 -- 01 11
   5 tikov                                4.0     21.00  01 01 00 10 -- 01
   6 VirutorChessUci_1.1.2                2.5     12.50  0= 00 01 00 10 --

 =================================================================================================== 
  Nr Engine                               Pts      SB    pier tole Neur irin Viru tiko
   1 pierre17                            13.0     68.50  ---- 01 01 1111 1111 1011
   2 toledo_nanochess_wb                 10.5     67.25  10 ---- 11=1 1= 1= 1011
   3 Neurone_XXVI                         8.0     46.75  10 00=0 ---- =0 1111 011
   4 irina                                5.0     29.75  0000 0= =1 ---- 1000 11
   5 VirutorChessUci_1.1.2                4.5     24.25  0000 0= 0000 0111 ---- 10
   6 tikov                                4.0     36.00  0100 0100 100 00 01 ----

 =================================================================================================== 
  Nr Engine                               Pts      SB    tole pier Neur irin Viru tiko
   1 toledo_nanochess_wb                 14.5    132.75  ---- 1011 11=1 1=01 1=01 1011
   2 pierre17                            14.0    116.50  0100 ---- 0110 1111 1111 1011
   3 Neurone_XXVI                         9.5     84.75  00=0 1001 ---- =0=0 1111 0110
   4 irina                                9.5     77.75  0=10 0000 =1=1 ---- 1000 1111
   5 VirutorChessUci_1.1.2                7.5     65.25  0=10 0000 0000 0111 ---- 1011
   6 tikov                                5.0     55.00  0100 0100 1001 0000 0100 ----

 =================================================================================================== 
  Nr Engine                               Pts      SB    toledo pierre Neuron Viruto irina tikov
   1 toledo_nanochess_wb                 18.0    198.50  ------ 1011 11=1=1 1=01 1=01 101111
   2 pierre17                            17.0    172.00  0100 ------ 0110 111100 111111 101101
   3 Neurone_XXVI                        13.0    146.00  00=0=0 1001 ------ 111111 =0=0 01101
   4 VirutorChessUci_1.1.2               11.0    124.00  0=10 000011 000000 ------ 0111=1 1011
   5 irina                               10.0    106.50  0=10 000000 =1=1 1000=0 ------ 1111
   6 tikov                                6.0     89.00  010000 010010 10010 0100 0000 ------

 =================================================================================================== 
  Nr Engine                               Pts      SB    toledo pierre Neuron irina Viruto tikov
   1 toledo_nanochess_wb                 23.0    302.50  ------ 101110 11=1=1 1=0111 1=0111 101111
   2 pierre17                            20.0    260.00  010001 ------ 011011 111111 111100 101101
   3 Neurone_XXVI                        14.0    185.00  00=0=0 100100 ------ =0=001 111111 011010
   4 irina                               13.0    156.50  0=1000 000000 =1=110 ------ 1000=0 111111
   5 VirutorChessUci_1.1.2               12.0    165.00  0=1000 000011 000000 0111=1 ------ 101110
   6 tikov                                8.0    129.00  010000 010010 100101 000000 010001 ------

 =================================================================================================== 
  Nr Engine                               Pts      SB    toledo_n pierre17 VirutorC Neurone_ irina tikov
   1 toledo_nanochess_wb                 27.0    401.50  -------- 101110 1=0111 11=1=111 1=0111 10111111
   2 pierre17                            24.0    351.00  010001 -------- 11110010 011011 11111111 10110101
   3 VirutorChessUci_1.1.2               15.0    244.50  0=1000 00001101 -------- 00000010 0111=110 101110
   4 Neurone_XXVI                        15.0    238.00  00=0=000 100100 11111101 -------- =0=001 0110100
   5 irina                               14.0    198.00  0=1000 00000000 1000=001 =1=110 -------- 111111
   6 tikov                               10.0    189.00  01000000 01001010 010001 1001011 000000 --------

 =================================================================================================== 
  Nr Engine                               Pts      SB    toledo_n pierre17 VirutorC Neurone_ irina tikov
   1 toledo_nanochess_wb                 31.5    550.50  -------- 10111011 1=011101 11=1=111 1=01111= 10111111
   2 pierre17                            26.0    440.50  01000100 -------- 11110010 01101111 11111111 10110101
   3 VirutorChessUci_1.1.2               18.0    330.75  0=100010 00001101 -------- 00000010 0111=110 10111011
   4 Neurone_XXVI                        17.0    303.50  00=0=000 10010000 11111101 -------- =0=00110 01101001
   5 irina                               16.0    267.75  0=10000= 00000000 1000=001 =1=11001 -------- 1111110=
   6 tikov                               11.5    237.50  01000000 01001010 01000100 10010110 0000001= --------

 =================================================================================================== 
  Nr Engine                               Pts      SB    toledo_nan pierre17 VirutorChe Neurone_XX irina tikov
   1 toledo_nanochess_wb                 35.5    681.00  ---------- 10111011 1=011101 11=1=11111 1=01111= 1011111111
   2 pierre17                            29.0    548.00  01000100 ---------- 1111001001 01101111 1111111110 1011010110
   3 VirutorChessUci_1.1.2               21.0    438.75  0=100010 0000110110 ---------- 0000001010 0111=11001 10111011
   4 Neurone_XXVI                        18.0    369.50  00=0=00000 10010000 1111110101 ---------- =0=00110 011010010
   5 irina                               18.0    351.25  0=10000= 0000000001 1000=00110 =1=11001 ---------- 1111110=
   6 tikov                               13.5    310.50  0100000000 0100101001 01000100 100101101 0000001= ----------

 =================================================================================================== 
  Nr Engine                               Pts      SB    toledo_nan pierre17 VirutorChe Neurone_XX irina tikov
   1 toledo_nanochess_wb                 40.5    875.00  ---------- 1011101111 1=01110101 11=1=11111 1=01111=11 1011111111
   2 pierre17                            30.0    640.00  0100010000 ---------- 1111001001 0110111101 1111111110 1011010110
   3 VirutorChessUci_1.1.2               24.0    552.00  0=10001010 0000110110 ---------- 0000001010 0111=11001 1011101111
   4 Neurone_XXVI                        20.5    472.75  00=0=00000 1001000010 1111110101 ---------- =0=001101= 0110100100
   5 irina                               20.5    431.00  0=10000=00 0000000001 1000=00110 =1=110010= ---------- 1111110=11
   6 tikov                               14.5    362.25  0100000000 0100101001 0100010000 1001011011 0000001=00 ----------

**Comment by lukasmonk** [comment]
Fixed time forfeit and 3-fold rep.
