### ISSUE TITLE
The command 'ucinewgame' is not handled correctly

### ISSUE THREAD

**Issue by rchastain** [lukasmonk/irina#2]
Hello!

If you start _Irina_ from a terminal, and type **ucinewgame**, you will see that the program answers to the **uci** command.
There is a very simple fix. In _loop.c,_ we have to change the conditions order like this:

```c
        if (SCAN("ucinewgame"))
        {
        }
        else if (SCAN("uci"))
        {
        }
```

Regards.

Roland

**Comment by lukasmonk** [comment]
Thanks Roland, fixed.

**Comment by rchastain** [comment]
You are welcome. I close the issue. See you!
