### ISSUE TITLE
compile on Linux 64-bit ?

### ISSUE THREAD

**Issue by tissatussa** [lukasmonk/irina#3]
to compile on Linux, i removed the line "#include <windows.h>", which isn't needed on Linux .. but i get more errors, can these be solved ? The Makefile even seems to address 32-bit code, am i right ? I'm on Xubuntu 22.04, 64-bit.

```c
~/Compiled/irina/src$ make all
gcc -Wall -O3 -o main.o -c main.c -DNDEBUG -DWIN32
gcc -Wall -O3 -o loop.o -c loop.c -DNDEBUG -DWIN32
In file included from loop.c:11:
defs.h:15:20: error: conflicting types for ‘int64_t’; have ‘long long int’
   15 | typedef long long  int64_t;
      |                    ^~~~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:155,
                 from /usr/include/stdlib.h:395,
                 from loop.c:2:
/usr/include/x86_64-linux-gnu/bits/stdint-intn.h:27:19: note: previous declaration of ‘int64_t’ with type ‘int64_t’ {aka ‘long int’}
   27 | typedef __int64_t int64_t;
      |                   ^~~~~~~
loop.c: In function ‘loop’:
loop.c:70:17: warning: implicit declaration of function ‘Sleep’ [-Wimplicit-function-declaration]
   70 |                 Sleep(100);
      |                 ^~~~~
loop.c: In function ‘go’:
loop.c:301:17: error: ‘INFINITE’ undeclared (first use in this function)
  301 |         depth = INFINITE;
      |                 ^~~~~~~~
loop.c:301:17: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:19: loop.o] Error 1
```

**Comment by rchastain** [comment]
Hello!

I suggest to modify the _Makefile_. Remove `.exe` (line 1) and  `-DWIN32` (line 19). After that it compiles without error, and without editing the source code.

**Comment by rchastain** [comment]
For me, I renamed the original _Makefile_ to _Makefile.win_, in case I need it.

**Comment by tissatussa** [comment]
that way i get less errors, but some `int64_t` is still wrong :

```c
~/Compiled/irina/src$ make all
gcc -Wall -O3 -o main.o -c main.c -DNDEBUG
gcc -Wall -O3 -o loop.o -c loop.c -DNDEBUG
In file included from loop.c:11:
defs.h:15:20: error: conflicting types for ‘int64_t’; have ‘long long int’
   15 | typedef long long  int64_t;
      |                    ^~~~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:155,
                 from /usr/include/stdlib.h:395,
                 from loop.c:2:
/usr/include/x86_64-linux-gnu/bits/stdint-intn.h:27:19: note: previous declaration of ‘int64_t’ with type ‘int64_t’ {aka ‘long int’}
   27 | typedef __int64_t int64_t;
      |                   ^~~~~~~
make: *** [Makefile:19: loop.o] Error 1
```

once i was searching a solution for a similar issue in some other code .. i didn't succeed, but i'm not familiar with C .. does alternative code exist to make it run on Linux 64-bit ?

**Comment by rchastain** [comment]
Yes, you are right. With a fresh copy of the source code I get the same error. It seems that something was broken in a recent commit.

**Comment by rchastain** [comment]
I must leave. Here is the version that I have on my HD, if you wish to take a look.

[src.zip](https://github.com/lukasmonk/irina/files/10698160/src.zip)

**Comment by tissatussa** [comment]
that source code helped ! By the Meld tool (=GUI for diff) i discovered you just disabled the line `typedef long long int64_t;` in the file `defs.h` .. so i did, and now compilation went well : i get a valid binary v0.15 !

**Comment by rchastain** [comment]
Thanks for the confirmation (and for the tip about Meld).

**Comment by tissatussa** [comment]
> ..the tip about Meld

yes, Meld is a rather famous "Visual diff and merge tool" which can help in many cases to get insights in file sets & folder structures, really nice : https://meldmerge.org

glad to help, and thanks !
-you can close the Issue now-

**Comment by rchastain** [comment]
I cannot close: this is not my repository. But you can close. See you!
